name: www.garethdavies.me
url: http://www.garethdavies.me
markdown: redcarpet
pygments: true
exclude: [scss, README.md, node_modules, package.json, Gruntfile.js, fontello.css, normalize.css]
paginate: 6
paginate_path: "blog/page:num"
sitemap:
  include_posts:
    - "/index.html"
    - "/blog/index.html"